### ISSUE TITLE
Why do you use int IDs instead of registry names?

### ISSUE THREAD

**Issue by Prospector** [Team-RTG/Lonely-Biome#10]
For mod-added biomes, Forge dynamically assigns integer ids, making this mod pretty much incompatible with any biome mod using proper forge registries. I assume this was an oversight when it was ported along the way.

**Comment by srs-bsns** [comment]
My dev version that hasn't been merged yet has been using ResourceLocation names for months.

There is an outstanding bug that has delayed merging that PR, and since this mod has a low demand and with other projects taking priority, it has just been left in it's current state. It will be released eventually, but probably not until after RTG has been updated to 1.12.
